/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.examples.mw

class Library {
    fun someLibraryMethod(): Boolean {
        println(com.examples.mw.common.mymax(4, 5)) // use code from module "motive.wave.custom.common"
        return true
    }
}
